# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

defaults:
  run: 
    shell: bash
    working-directory: ./cgWebShop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CONNECTION_STRING: "Server=localhost;Port=5432;User Id=postgres;Password=postgres;Database=cgwebshop"
      VALID_ISSUER: "CgWebSHopAudience"
      VALID_AUDIENCE: "CgWebSHopIssuer"
      ISSUER_SIGNING_KEY: "CgWebShop!Issuer!Secret??Signing-Key"
      ROLE_1: "Admin"
      ROLE_2: "User"

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Print Environment Variables
      run: printenv
    - name: Test
      run: dotnet test --no-build --verbosity normal
